---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/service-widgets/ https://gethomepage.dev/en/configs/widgets/

- resources:
  cpu: true
  memory: true
  disk: /

- search:
  provider: custom
  url: https://search.casjay.net/?q=
  target: _blank

- datetime:
  format:
    dateStyle: short
    timeStyle: short
    hour12: false
